version: "3.8"

services:
  api:
    build:
      context: ./apps/api
    volumes:
      - ./apps/api:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "9000:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  web:
    # If apps/web has a Dockerfile it will be used. If not, Compose won't fail; build will be skipped if Dockerfile absent.
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9000
    depends_on:
      - api

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:


